### ISSUE TITLE
Problema com o envio do certificado/reconhecimento CSV

### ISSUE THREAD

**Issue by sntccschstr** [ratodigital/certificadospdf#2]
Boa noite, 
estou tentando criar meus certificados para um curso de línguas. Consegui fazer, como explica o vídeo, o Template e o arquivo .CSV. Porém, quando dou o PREVIEW, ele não preenche os campos, e não recebo, também, qualquer e-mail com o certificado. Você poderia me ajudar? Creio que o erro deve estar dando com o csv, mas não sei explicar o porquê :(

Grata,

Att.

**Comment by sergerehem** [comment]
Olá, 

Eu estava fazendo uma limpa aqui nos meus emails e assuntos ligados ao CertificadosPDF e só hoje via sua mensagem, que pelo jeito ficou sem resposta. Peço desculpas.

Sei que perdi o "timing" completamente. O CertificadosPDF é um projeto voluntário e nem sempre eu consegui dar a atenção devida a todos que me fizeram alguma solicitação. 

Só que agora isso está prestes a mudar, então aproveito pra informar que o CertificadosPDF está ficando muito melhor.

Vem aí o GeradordeCertificados.com.br.

Se vc tiver interesse em ganhar uma licença PRO gratuita com envios ilimitados de e-mails, por favor entre em contato. 

Estamos com uma novidade para quem como você já usava o CertificadosPDF.

Abraço
Serge
